#
# Makefile for the Goodix gt917d touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT917d)		+= gt917d.o
obj-$(CONFIG_TOUCHSCREEN_GT917d)		+= gt917d_update.o
obj-$(CONFIG_TOUCHSCREEN_GT917d)		+= goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_GT917d)		+= gt917d_openshort.o
